### ISSUE TITLE
Data from Google Scholar

### ISSUE THREAD

**Issue by favstats** [dhaine/website#1]
Hi there! I just came across your [blogpost](https://www.denishaine.ca/blog/popepi-rmd/) on comparing the use of R and other languages in Google Scholar. I was wondering how you accessed the data? Is there an R package or did you set up a scraper yourself? Maybe I missed it but I couldn't see it in your blogpost.

Best,

Fabio

**Comment by dhaine** [comment]
Hello Fabio,

To my knowledge there's no package for this, or available scraper code
somewhere. I just collected the info "by hand"!
Cheers,

Denis
